# Use a lightweight Node.js image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the Node port (handled by docker-compose, but good practice) #???????????????????
EXPOSE 3000 

# Start the server
CMD ["node", "app.js"]