const restaurantModel = require('./restaurant.model');
/**
 * Product Data Model.
 * Manages the creation and structure of product entities.
 * Note: Storage is handled internally within the Restaurant model.
 */
class ProductModel {
    constructor() {}

    /**
     * Creates a new Product entity object.
     * @param {Object} productData - The verified data for the new product.
     * @param {string} generatedId - The UUID generated by the service.
     * @returns {Object} The newly created product object.
     */
    createProduct(productData, generatedId) {
        const newProduct = {
            id: generatedId,
            name: productData.name,
            description: productData.description || '',
            price: productData.price
        };

        return newProduct;
    }
}  

module.exports = new ProductModel();