/**
 * Restaurant Data Model.
 */
class RestaurantModel {
    constructor() {
        /**
         * Internal Map to store all restaurants.
         * Key: Restaurant ID (UUID)
         * Value: Restaurant Object
         */
        this.restaurants = new Map();
    }

    /**
     * Creates a new restaurant entity and stores it in the map.
     * @param {Object} restaurantData - The verified data for the new restaurant.
     * @param {string} restaurantData.id - The unique UUID generated by the service.
     * @param {string} restaurantData.name - The name of the restaurant.
     * @param {string} restaurantData.description - A short description for search queries.
     * @param {string} restaurantData.address - The physical address of the restaurant.
     * @param {string} restaurantData.phone - The contact phone number for the restaurant.
     * @param {boolean} restaurantData.kosher - Kosher certification status.
     * @returns {Object} The newly created restaurant object.
     */
    createRestaurant(restaurantData) {
        // Constructing the exact Restaurant object structure
        const newRestaurant = {
            id: restaurantData.id,
            name: restaurantData.name,
            description: restaurantData.description,
            address: restaurantData.address,
            phone: restaurantData.phone,
            kosher: restaurantData.kosher,
            working_hours: restaurantData.working_hours,
            rating: 0, // Initial rating is set to 0

            /**
             * Internal Map to store the menu products for this specific restaurant.
             * Key: Product ID (UUID)
             * Value: Product Object
             */
            products: new Map()
        };

        // Store the newly created restaurant in our main in-memory Map
        this.restaurants.set(newRestaurant.id, newRestaurant);
        
        return newRestaurant;
    }

   getAllRestaurants() {
        return this.restaurants;
    }
	
	getRestaurantById(id) {
		return this.restaurants.get(id)
	}
	
	updateRestaurant(id, updatedRestaurant) {
        this.restaurants.set(id, updatedRestaurant);
        return updatedRestaurant;
    }
	
	deleteRestaurant(id){
		this.restaurants.delete(id);
	}
}

module.exports = new RestaurantModel();