/**
 * User Data Model.
 * Manages the in-memory storage of users using a Map for O(1) operations.
 */
class UserModel {
    constructor() {
        /**
         * Internal Map to store all users.
         * Key: User ID (UUID)
         * Value: User Object { id, username, password, name, phone, address }
         */
        this.users = new Map();
    }

    /**
     * Creates a new User entity and stores it in the map.
     * @param {Object} userData - The verified data for the new user.
     * @param {string} userData.id - The unique UUID generated by the service.
     * @param {string} userData.username - The username for the user.
     * @param {string} userData.password - The password for the user.
     * @param {string} userData.name - The name of the user.
     * @param {string} userData.phone - The phone number of the user.
     * @param {string} userData.address - The physical address of the user.
     * @param {string} userData.role - The role of the user (e.g., 'user', 'admin').
     * @param {string} userData.picture - The Base64 encoded profile picture of the user.
     * @returns {Object} The newly created user object.
     */
    createUser(userData){
        // Constructing the exact User object structure
        const newUser = {
            id: userData.id,
            username: userData.username,
            password: userData.password,
            name: userData.name,
            phone: userData.phone,
            address: userData.address,
            role: userData.role || 'user', // default role is 'user', can be overridden by service if needed
            picture: userData.picture,
            coordinates: userData.coordinates || { lat: 0, lng: 0 }
        };

        // Store the newly created user in our main in-memory Map
        this.users.set(newUser.id, newUser);
        
        return newUser;
    }
    
    getUserById(id) {
        return this.users.get(id);
    }
    
    getUserByUsername(username) {
        for (const user of this.users.values()) {
            if (user.username === username) {
                return user;
            }
        }
        return null;
    }
}

module.exports = new UserModel();