/**
 * User Data Model.
 * Manages the in-memory storage of users using a Map for O(1) operations.
 */
class UserModel {
    constructor() {
        /**
         * Internal Map to store all users.
         * Key: User ID (UUID)
         * Value: User Object { id, username, password, name, phone, addressX, addressY }
         */
        this.users = new Map();

        // Seed initial mock users for testing
        this._seedMockUsers();
    }

    /**
     * Seeds initial mock users into the database.
     * @private
     */
    _seedMockUsers() {
        const mockUser = {
            id: 'mock-user-id-1',
            username: 'user',
            password: '1234',
            name: 'Regular User',
            phone: '0501234567',
            addressX: 12.34,
            addressY: 56.78,
            role: 'user',
            picture: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="%2300c2e8"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="20" fill="white">U</text></svg>'
        };

        const mockOwner = {
            id: 'mock-owner-id-2',
            username: 'admin',
            password: '1234',
            name: 'Restaurant Owner',
            phone: '0507654321',
            addressX: 34.56,
            addressY: 78.90,
            role: 'restaurant_owner',
            picture: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="%23e800c2"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="20" fill="white">O</text></svg>'
        };

        this.users.set(mockUser.id, mockUser);
        this.users.set(mockOwner.id, mockOwner);
    }

    /**
     * Creates a new User entity and stores it in the map.
     * @param {Object} userData - The verified data for the new user.
     * @param {string} userData.id - The unique UUID generated by the service.
     * @param {string} userData.username - The username for the user.
     * @param {string} userData.password - The password for the user.
     * @param {string} userData.name - The name of the user.
     * @param {string} userData.phone - The phone number of the user.
     * @param {number} userData.addressX - The X coordinate of the user's address.
     * @param {number} userData.addressY - The Y coordinate of the user's address.
     * @param {string} userData.role - The role of the user (e.g., 'user', 'restaurant_owner').
     * @param {string} userData.picture - The Base64 encoded profile picture of the user.
     * @returns {Object} The newly created user object.
     */
    createUser(userData){
        // Constructing the exact User object structure
        const newUser = {
            id: userData.id,
            username: userData.username,
            password: userData.password,
            name: userData.name,
            phone: userData.phone,
            addressX: userData.addressX,
            addressY: userData.addressY,
            role: userData.role || 'user', // default role is 'user', can be overridden by service if needed
            picture: userData.picture
        };

        // Store the newly created user in our main in-memory Map
        this.users.set(newUser.id, newUser);
        
        return newUser;
    }
    
    getUserById(id) {
        return this.users.get(id);
    }
    
    getUserByUsername(username) {
        for (const user of this.users.values()) {
            if (user.username === username) {
                return user;
            }
        }
        return null;
    }

    /**
     * Updates an existing user with new field values.
     * @param {string} id - The user ID.
     * @param {Object} updatedFields - The fields to update.
     * @returns {Object|null} The updated user object, or null if not found.
     */
    updateUser(id, updatedFields) {
        const user = this.getUserById(id);
        if (!user) return null;

        const updatedUser = { ...user, ...updatedFields };
        this.users.set(id, updatedUser);
        return updatedUser;
    }
}

module.exports = new UserModel();