/**
 * User Data Model.
 * Manages the in-memory storage of users using a Map for O(1) operations.
 */
class UserModel {
    constructor() {
        /**
         * Internal Map to store all users.
         * Key: User ID (UUID)
         * Value: User Object { id, username, password, name, phone, addressX, addressY }
         */
        this.users = new Map();

    }



    /**
     * Creates a new User entity and stores it in the map.
     * @param {Object} userData - The verified data for the new user.
     * @param {string} userData.id - The unique UUID generated by the service.
     * @param {string} userData.username - The username for the user.
     * @param {string} userData.password - The password for the user.
     * @param {string} userData.name - The name of the user.
     * @param {string} userData.phone - The phone number of the user.
     * @param {number} userData.addressX - The X coordinate of the user's address.
     * @param {number} userData.addressY - The Y coordinate of the user's address.
     * @param {string} userData.role - The role of the user (e.g., 'user', 'restaurant_owner').
     * @param {string} userData.picture - The Base64 encoded profile picture of the user.
     * @returns {Object} The newly created user object.
     */
    createUser(userData){
        // Constructing the exact User object structure
        const newUser = {
            id: userData.id,
            username: userData.username,
            password: userData.password,
            name: userData.name,
            phone: userData.phone,
            addressX: userData.addressX,
            addressY: userData.addressY,
            role: userData.role || 'user', // default role is 'user', can be overridden by service if needed
            picture: userData.picture
        };

        // Store the newly created user in our main in-memory Map
        this.users.set(newUser.id, newUser);
        
        return newUser;
    }
    
    getUserById(id) {
        return this.users.get(id);
    }
    
    getUserByUsername(username) {
        for (const user of this.users.values()) {
            if (user.username === username) {
                return user;
            }
        }
        return null;
    }

    /**
     * Updates an existing user with new field values.
     * @param {string} id - The user ID.
     * @param {Object} updatedFields - The fields to update.
     * @returns {Object|null} The updated user object, or null if not found.
     */
    updateUser(id, updatedFields) {
        const user = this.getUserById(id);
        if (!user) return null;

        const updatedUser = { ...user, ...updatedFields };
        this.users.set(id, updatedUser);
        return updatedUser;
    }
}

module.exports = new UserModel();